server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: order-service-route
              uri: http://localhost:8081
              predicates:
                - Path=/orders/**